### ISSUE TITLE
Running apptainer image without the GPU

### ISSUE THREAD

**Issue by ajasja** [baker-laboratory/rf_diffusion_all_atom#11]
When I try to run the example in the redme I get an error (the only difference is probably that I run with a GPU).  Is this expected?

Apptainer version is:  1.3.0-1.el8

```
aljubetic@compute-4-1:~/RFDiffAA (main) 
$ /usr/bin/apptainer run rf_se3_diffusion.sif -u run_inference.py inference.deterministic=True diffuser.T=100 inference.output_prefix=output/ligand_only/sample inference.input_pdb=input/7v11.pdb contigmap.contigs=[\'150-150\'] inference.ligand=OQO inference.num_designs=1 inference.design_startnum=0
[15:28:15] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /opt/conda/envs/env/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.13.1.so: cannot open shared object file: No such file or directory
Using backend: pytorch
Traceback (most recent call last):
  File "/home/aljubetic/RFDiffAA/run_inference.py", line 27, in <module>
    from inference import utils as iu
  File "/home/aljubetic/RFDiffAA/inference/utils.py", line 9, in <module>
    from diffusion import get_beta_schedule, get_chi_betaT
  File "/home/aljubetic/RFDiffAA/diffusion.py", line 19, in <module>
    from util_module import ComputeAllAtomCoords
  File "/home/aljubetic/RFDiffAA/util_module.py", line 7, in <module>
    import dgl
  File "/opt/conda/envs/env/lib/python3.9/site-packages/dgl/__init__.py", line 16, in <module>
    from . import contrib
  File "/opt/conda/envs/env/lib/python3.9/site-packages/dgl/contrib/__init__.py", line 2, in <module>
    from . import graph_store
  File "/opt/conda/envs/env/lib/python3.9/site-packages/dgl/contrib/graph_store.py", line 5, in <module>
    from xmlrpc.server import SimpleXMLRPCServer
  File "/usr/lib/python3.9/xmlrpc/server.py", line 117, in <module>
    import pydoc
  File "/usr/lib/python3.9/pydoc.py", line 458, in <module>
    class Doc:
  File "/usr/lib/python3.9/pydoc.py", line 488, in Doc
    def getdocloc(self, object, basedir=sysconfig.get_path('stdlib')):
  File "/usr/lib/python3.9/sysconfig.py", line 519, in get_path
    return get_paths(scheme, vars, expand)[name]
  File "/usr/lib/python3.9/sysconfig.py", line 509, in get_paths
    return _expand_vars(scheme, vars)
  File "/usr/lib/python3.9/sysconfig.py", line 170, in _expand_vars
    _extend_dict(vars, get_config_vars())
  File "/usr/lib/python3.9/sysconfig.py", line 559, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python3.9/sysconfig.py", line 428, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata_x86_64_conda_cos7_linux_gnu'
```

**Comment by kevin-dyer** [comment]
Hello, I have also run into this error when trying to execute the example in the readme on a macbook with no external GPU attached. Is there any solution to this error?
Apptainer version is: 1.3.4
