### ISSUE TITLE
Can RFAA do partial diffusion?

### ISSUE THREAD

**Issue by ShuhaoGithub** [baker-laboratory/rf_diffusion_all_atom#19]
Can RFAA do partial diffusion as in noise-denoise an existing ligand-bound structure to get a better backbone?

**Comment by zhang-bo-lilly** [comment]
I believe this is the section related to partial diffusion. 

https://github.com/baker-laboratory/rf_diffusion_all_atom/blob/f913a19e16f30858ce7a724fe028475b1871319c/config/inference/base.yaml#L98-L113

**Comment by LiorZ** [comment]
Using diffuser.partial_T=40 in the command line (or whatever) should work

**Comment by Mistletoe-git** [comment]
Hello!

I added `diffuser.partial_T=40` to the design parameters of the unused partial diffusion of the original design, and it reported an error. Does anyone know the reason?

> Error message as follows:
> Traceback (most recent call last):
> File "D:\rf_diffusion_all_atom\run_inference.py", line 75, in main
> sample(sampler)
> File "D:\rf_diffusion_all_atom\run_inference.py", line 117, in sample
> sampler_out = sample_one(sampler)
> File "D:\rf_diffusion_all_atom\run_inference.py", line 123, in sample_one
> indep = sampler.sample_init()
> File "D:\rf_diffusion_all_atom\inference\model_runners.py", line 249, in sample_init
> assert indep.xyz.shape[0] == L + torch.sum(indep.is_sm), f"there must be a coordinate in the input PDB for each residue implied by the contig string for partial diffusion. length of input PDB != length of contig string: {indep.xyz.shape[0]} != {L+torch.sum(indep.is_sm)}"
> AssertionError: There must be a coordinate in the input PDB for each residue implied by the contig string for partial diffusion. Length of input PDB does not match length of contig string: 583 != 577
> >
> Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

I checked my pdb file and parameters, maybe because I increased the number of amino acids during the design, and the requirement of the partial diffusion for the number of amino acids in the designed protein to be completely consistent with the number in the reference structure?
