### ISSUE TITLE
Binder Design with PDB ID: 1D12 and Ligand DM2

### ISSUE THREAD

**Issue by amelie-iska** [baker-laboratory/rf_diffusion_all_atom#4]
I am attempting to design a binder for the ligand DM2 in this PDB: https://www.rcsb.org/structure/1D12

When I run the following command:
```
python run_inference.py \
    inference.deterministic=True \
    diffuser.T=100 \
    inference.output_prefix=output/ligand_only/DM2 \
    inference.input_pdb=input/1d12.pdb \
    contigmap.contigs=['150-150'] \
    inference.ligand=DM2 \
    inference.num_designs=1 \
    inference.design_startnum=0
```
I get the following error:
```
Error executing job with overrides: ['inference.deterministic=True', 'diffuser.T=100', 'inference.output_prefix=output/ligand_only/DM2', 'inference.input_pdb=input/1d12.pdb', 'contigmap.contigs=[150-150]', 'inference.ligand=DM2', 'inference.num_designs=1', 'inference.design_startnum=0']
Traceback (most recent call last):
  File "/opt/home/asr50/workspace/proteins/rf_diffusion_all_atom/run_inference.py", line 74, in main
    sampler = get_sampler(conf)
  File "/opt/home/asr50/workspace/proteins/rf_diffusion_all_atom/run_inference.py", line 96, in get_sampler
    sampler = inference.model_runners.sampler_selector(conf)
  File "/opt/home/asr50/workspace/proteins/rf_diffusion_all_atom/inference/model_runners.py", line 358, in sampler_selector
    sampler = NRBStyleSelfCond(conf)
  File "/opt/home/asr50/workspace/proteins/rf_diffusion_all_atom/inference/model_runners.py", line 41, in __init__
    self.initialize(conf)
  File "/opt/home/asr50/workspace/proteins/rf_diffusion_all_atom/inference/model_runners.py", line 83, in initialize
    self.target_feats = iu.process_target(self.inf_conf.input_pdb, parse_hetatom=False, center=False)
  File "/opt/home/asr50/workspace/proteins/rf_diffusion_all_atom/inference/utils.py", line 919, in process_target
    target_struct = parse_pdb(pdb_path, parse_hetatom=parse_hetatom)
  File "/opt/home/asr50/workspace/proteins/rf_diffusion_all_atom/inference/utils.py", line 780, in parse_pdb
    return parse_pdb_lines(lines, **kwargs)
  File "/opt/home/asr50/workspace/proteins/rf_diffusion_all_atom/inference/utils.py", line 794, in parse_pdb_lines
    idx = pdb_idx.index((chain,resNo))
ValueError: ('A', 1) is not in list

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```
What am I doing wrong?

**Comment by ikalvet** [comment]
Thank you for giving it a try!
Performing free diffusion around a ligand still (unfortunately) requires at least one amino acid to be present as residue A1 in the input PDB. It can be placed there completely randomly, and since it's not referenced in the contigs then it also won't affect the generated structures.

**Comment by amelie-iska** [comment]
Had to try a few different things to get this to work. Ultimately, I simply replaced every ATOM entry before the TER line with the following generic residue:
```
ATOM      1  N   ALA A   1      10.000  10.000  10.000  1.00  0.00           N  
ATOM      2  CA  ALA A   1      11.000  10.000  10.000  1.00  0.00           C  
ATOM      3  C   ALA A   1      11.000  11.000  10.000  1.00  0.00           C  
ATOM      4  O   ALA A   1      11.000  11.000  11.000  1.00  0.00           O  
ATOM      5  CB  ALA A   1      11.000  10.000   9.000  1.00  0.00           C     
TER     121       DG A   6 
```
This ended up working. Not sure if there was a better way to do this, but at least this worked.
